Working
AAlchi/hshacks-signup-form pull request #3
Opened 2024-10-07 21:07 UTC by ostapzhp

2024-10-07 23:09 UTC, AAlchi requested changes
Great work on this; I left some feedback, but don't feel pressured to do everything before the meetup if it's too much.

2024-10-07 23:09 UTC, AAlchi commented on pages/index.tsx
> +      <Header></Header>
Something that can clean up the code and is a good habit to get into is keeping the header as
```typescript
<Header />
```

2024-10-07 23:09 UTC, AAlchi commented on pages/index.tsx
> +      <div className="flex items-center justify-center bg-none">
You didn't have to write out all of the questions as long as the component is working, but what we can do is comment this out for now and assign a task related to this during our next meeting so you don't lose your work.

2024-10-07 23:09 UTC, AAlchi commented on pages/components/RadioComponent/RadioComponent.tsx
Looks great! One thing I'd add is a way to get the data back so that we know what the user picked. Another thing you can do is add some styling; like bolding the question, or something like that. Overall, this functions well and it looks great

2024-10-07 23:09 UTC, AAlchi commented on pages/index.tsx
>          <title>Sign Up</title>
It would match the link better if this was "Register" instead of "Sign Up"; I apologize for not mentioning that earlier.

2024-10-07 23:09 UTC, AAlchi commented on pages/index.tsx
The index.ts page is essentially the main page for the website (hshacks.org). If you create a folder called "register" in the "pages" folder, and then add a index.ts inside the "register" folder, it will recognize it as a page (hshacks.org/register). That way, this code can be moved there to match the website.

Inside the register folder, you can have the exact same code as this page (with some exceptions like the import links that need to be changed and without the ``` <Header /> and <Footer /> ``` 

Once that's all done, you can remove everything related to signup on this page and replace it with the  ```<Register /> ``` page

2024-10-09 21:26 UTC, ostapzhp commented
Changed and added everything that was asked

2024-10-10 22:38 UTC, AAlchi approved these changes

2024-10-10 22:39 UTC, merged